[
    {
        "id": 3,
        "product_id": 2,
        "rating": 4,
        "date": "2020-12-30T10:57:31.000Z",
        "summary": "I am liking these glasses",
        "body": "They are very dark.  But that's good because I'm in very sunny spots",
        "recommend": "true",
        "reported": "false",
        "reviewer_name": "bigbrotherbenjamin",
        "reviewer_email": "first.last@gmail.com",
        "response": "Glad you're enjoying the product!",
        "helpfulness": 5,
        "characteristic_id": 5,
        "value": 4,
        "url": null
    },
    {
        "id": 4,
        "product_id": 2,
        "rating": 4,
        "date": "2020-07-01T18:34:45.000Z",
        "summary": "They look good on me",
        "body": "I so stylish and just my aesthetic.",
        "recommend": "true",
        "reported": "false",
        "reviewer_name": "fashionperson",
        "reviewer_email": "first.last@gmail.com",
        "response": "null",
        "helpfulness": 1,
        "characteristic_id": 5,
        "value": 5,
        "url": null
    },
    {
        "id": 5,
        "product_id": 2,
        "rating": 3,
        "date": "2021-03-17T13:28:37.000Z",
        "summary": "I'm enjoying wearing these shades",
        "body": "Comfortable and practical.",
        "recommend": "true",
        "reported": "false",
        "reviewer_name": "shortandsweeet",
        "reviewer_email": "first.last@gmail.com",
        "response": "null",
        "helpfulness": 5,
        "characteristic_id": 5,
        "value": 5,
        "url": "https://images.unsplash.com/photo-1487349384428-12b47aca925e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80"
    },
    {
        "id": 5,
        "product_id": 2,
        "rating": 3,
        "date": "2021-03-17T13:28:37.000Z",
        "summary": "I'm enjoying wearing these shades",
        "body": "Comfortable and practical.",
        "recommend": "true",
        "reported": "false",
        "reviewer_name": "shortandsweeet",
        "reviewer_email": "first.last@gmail.com",
        "response": "null",
        "helpfulness": 5,
        "characteristic_id": 5,
        "value": 5,
        "url": "https://images.unsplash.com/photo-1560570803-7474c0f9af99?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=975&q=80"
    },
    {
        "id": 5,
        "product_id": 2,
        "rating": 3,
        "date": "2021-03-17T13:28:37.000Z",
        "summary": "I'm enjoying wearing these shades",
        "body": "Comfortable and practical.",
        "recommend": "true",
        "reported": "false",
        "reviewer_name": "shortandsweeet",
        "reviewer_email": "first.last@gmail.com",
        "response": "null",
        "helpfulness": 5,
        "characteristic_id": 5,
        "value": 5,
        "url": "https://images.unsplash.com/photo-1561693532-9ff59442a7db?ixlib=rb-1.2.1&auto=format&fit=crop&w=975&q=80"
    },
    {
        "id": 6,
        "product_id": 2,
        "rating": 5,
        "date": "2020-07-01T00:48:41.000Z",
        "summary": "I'm not a fan!",
        "body": "I don't like them",
        "recommend": "false",
        "reported": "false",
        "reviewer_name": "negativity",
        "reviewer_email": "first.last@gmail.com",
        "response": "Sorry to hear. Is there anything in particular you don't like?",
        "helpfulness": 0,
        "characteristic_id": 5,
        "value": 3,
        "url": null
    },
    {
        "id": 7,
        "product_id": 2,
        "rating": 2,
        "date": "2021-01-01T17:40:45.000Z",
        "summary": "This product was ok!",
        "body": "They're fine but I wouldn't buy again.",
        "recommend": "false",
        "reported": "false",
        "reviewer_name": "anyone",
        "reviewer_email": "first.last@gmail.com",
        "response": "null",
        "helpfulness": 0,
        "characteristic_id": 5,
        "value": 4,
        "url": null
    }
]